FROM everymatrix.jfrog.io/emlab-docker-remote-nvcr/nvidia/pytorch:24.12-py3
# https://ngc.nvidia.com/catalog/containers/nvidia:pytorch
# https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-11.html
CMD ["/bin/bash"]